pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
    // 모든 모듈에서 사용할 플러그인의 버전을 중앙에서 관리합니다.
    plugins {
        id 'org.springframework.boot' version '3.5.3'
        id 'io.spring.dependency-management' version '1.1.7'
    }
}

rootProject.name = 'sugang-system'

// --- 전체 서비스 모듈 목록 ---
// API(계약) 모듈
include 'services:course-service'
include 'services:student-service'
//include 'services:registration-service'
//include 'services:enrollment-service'

// 구현 서비스 모듈
include 'services:course-service'
include 'services:student-service'
//include 'services:registration-service'
//include 'services:enrollment-service''